# Generated by Django 4.2 on 2024-04-22 13:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('numero_reservation', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('numero_place', models.IntegerField()),
                ('date_reservation', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passager')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trajet')),
            ],
        ),
    ]
