# Generated by Django 4.2 on 2024-04-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_passager_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
